### PR TITLE
Candidate

### PR DESCRIPTION
**Pull request by tungripe**

### CODE REVIEW

**Comment by sawilde** [comment]
this is probably not the branch you are looking for

**Comment by tungripe** [comment]
hi sawilde,
can you please let me know which branch should i pull? I made some changes into myob SDK to fix a small issue in MYOB and would like to commit it.

Regards,
Tung

**Comment by sawilde** [comment]
**master** is the only branch you should pull or make pull requests to 

the candidate and release branches are used for producing particular builds and pushing to nuget etc.

**Comment by tungripe** [comment]
Thanks a lot. I was able to follow your instruction and commit my changes to the repository

**Pull request closed without merging**
